---
driver:
  name: vagrant
  customize:
    memory: 2048
  network:
    - ["forwarded_port", {guest: 9090, host: 9090}]

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04



suites:
  - name: default
    run_list:
      - recipe[prometheus-chef::default]
